// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'customer_vo.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

CustomerVO _$CustomerVOFromJson(Map<String, dynamic> json) => CustomerVO(
  customerId: (json['customer_id'] as num).toInt(),
  barcode: json['barcode'] as String,
  grade: (json['grade'] as num).toInt(),
  notes: json['notes'] as String,
  comments: json['comments'] as String,
  status: json['status'] == 1,
  custom1: json['custom1'] as String,
  custom2: json['custom2'] as String,
  inactive: json['inactive'] == 1,
  dateModified: json['date_modified'] as String,
  surname: json['surname'] as String,
  givenNames: json['given_names'] as String,
  position: json['position'] as String,
  company: json['company'] as String,
  salutation: json['salutation'] as String,
  account: json['account'] == 1,
  openedId: (json['opened_id'] as num).toInt(),
  ownerId: (json['owner_id'] as num).toInt(),
  limit: json['limit'] as num,
  days: (json['days'] as num).toInt(),
  fromEOM: json['from_eom'] == 1,
  addr1: json['addr1'] as String,
  addr2: json['addr2'] as String,
  addr3: json['addr3'] as String,
  suburb: json['suburb'] as String,
  state: json['state'] as String,
  postcode: json['postcode'] as String,
  country: json['country'] as String,
  phone: json['phone'] as String,
  fax: json['fax'] as String,
  mobile: json['mobile'] as String,
  email: json['email'] as String,
  abn: json['abn'] as String,
  overseas: json['overseas'] == 1,
  external: json['external'] == 1,
  dateCreated: json['date_created'] as String,
  isBarcodePrinted: json['is_barcode_printed'] == 1,
  documentDeliveryType: (json['document_delivery_type'] as num).toInt(),
  groupEmailExclusionId: (json['group_email_exclusion_id'] as num).toInt(),
  defaultDeliveryAddress: (json['default_delivery_address'] as num).toInt(),
  addresses: (json['addresses'] as List<dynamic>)
      .map((e) => CustomerAddressVO.fromJson(e as Map<String, dynamic>))
      .toList(),
);

CustomerVO _$CustomerVOFromJsonNetwork(Map<String, dynamic> json) => CustomerVO(
  customerId: (json['customer_id'] as num).toInt(),
  barcode: json['barcode'] as String,
  grade: (json['grade'] as num).toInt(),
  notes: json['notes'] as String,
  comments: json['comments'] as String,
  status: json['status'],
  custom1: json['custom1'] as String,
  custom2: json['custom2'] as String,
  inactive: json['inactive'],
  dateModified: json['date_modified'] as String,
  surname: json['surname'] as String,
  givenNames: json['given_names'] as String,
  position: json['position'] as String,
  company: json['company'] as String,
  salutation: json['salutation'] as String,
  account: json['account'],
  openedId: (json['opened_id'] as num).toInt(),
  ownerId: (json['owner_id'] as num).toInt(),
  limit: json['limit'] as num,
  days: (json['days'] as num).toInt(),
  fromEOM: json['from_eom'],
  addr1: json['addr1'] as String,
  addr2: json['addr2'] as String,
  addr3: json['addr3'] as String,
  suburb: json['suburb'] as String,
  state: json['state'] as String,
  postcode: json['postcode'] as String,
  country: json['country'] as String,
  phone: json['phone'] as String,
  fax: json['fax'] as String,
  mobile: json['mobile'] as String,
  email: json['email'] as String,
  abn: json['abn'] as String,
  overseas: json['overseas'],
  external: json['external'],
  dateCreated: json['date_created'] as String,
  isBarcodePrinted: json['is_barcode_printed'],
  documentDeliveryType: (json['document_delivery_type'] as num).toInt(),
  groupEmailExclusionId: (json['group_email_exclusion_id'] as num).toInt(),
  defaultDeliveryAddress: (json['default_delivery_address'] as num).toInt(),
  addresses: (json['addresses'] as List<dynamic>)
      .map((e) => CustomerAddressVO.fromJson(e as Map<String, dynamic>))
      .toList(),
);

Map<String, dynamic> _$CustomerVOToJson(
  CustomerVO instance,
  String currentShopfront,
) => <String, dynamic>{
  'customer_id': instance.customerId,
  'shopfront': currentShopfront,
  'barcode': instance.barcode,
  'grade': instance.grade,
  'notes': instance.notes,
  'comments': instance.comments,
  'status': instance.status ? 1 : 0,
  'custom1': instance.custom1,
  'custom2': instance.custom2,
  'inactive': instance.inactive ? 1 : 0,
  'date_modified': instance.dateModified,
  'surname': instance.surname,
  'given_names': instance.givenNames,
  'position': instance.position,
  'company': instance.company,
  'salutation': instance.salutation,
  'account': instance.account ? 1 : 0,
  'opened_id': instance.openedId,
  'owner_id': instance.ownerId,
  'limit': instance.limit,
  'days': instance.days,
  'from_eom': instance.fromEOM ? 1 : 0,
  'addr1': instance.addr1,
  'addr2': instance.addr2,
  'addr3': instance.addr3,
  'suburb': instance.suburb,
  'state': instance.state,
  'postcode': instance.postcode,
  'country': instance.country,
  'phone': instance.phone,
  'fax': instance.fax,
  'mobile': instance.mobile,
  'email': instance.email,
  'abn': instance.abn,
  'overseas': instance.overseas ? 1 : 0,
  'external': instance.external ? 1 : 0,
  'date_created': instance.dateCreated,
  'is_barcode_printed': instance.isBarcodePrinted ? 1 : 0,
  'document_delivery_type': instance.documentDeliveryType,
  'group_email_exclusion_id': instance.groupEmailExclusionId,
  'default_delivery_address': instance.defaultDeliveryAddress,
};
