// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'stock_vo.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

StockVO _$StockVOFromJson(Map<String, dynamic> json) => StockVO(
  stockID: json['stock_id'] as num,
  barcode: json['Barcode'] as String,
  description: json['description'] as String,
  deptName: json['dept_name'] as String,
  deptID: (json['dept_id'] as num).toInt(),
  custom1: json['custom1'] as String?,
  custom2: json['custom2'] as String?,
  longDescription: json['longdesc'] as String?,
  supplier: json['supplier'] as String,
  category1: json['cat1'] as String?,
  category2: json['cat2'] as String?,
  category3: json['cat3'] as String?,
  cost: (json['cost'] as num).toDouble(),
  sell: (json['sell'] as num).toDouble(),
  inactive: json['inactive'] == 1,
  quantity: json['quantity'] as num,
  laybyQuantity: json['layby_qty'] as num,
  salesOrderQuantity: json['salesorder_qty'] as num,
  dateCreated: json['date_created'] as String,
  orderThreshold: json['order_threshold'] as num,
  orderQuantity: json['order_quantity'] as num,
  allowFractions: json['allow_fractions'] == 1,
  package: json['package'] == 1,
  staticQuantity: json['static_quantity'] == 1,
  pictureFileName: json['picture_file_name'] as String?,
  imageUrl: json['imageUrl'] as String?,
  goodsTax: json['goods_tax'] as String?,
  salesTax: json['sales_tax'] as String?,
  dateModified: json['date_modified'] as String,
  freight: json['freight'] == 1,
  tareWeight: json['tare_weight'] as num,
  unitOfMeasure: json['unitof_measure'] as num,
  weighted: json['weighted'] == 1,
  trackSerial: json['track_serial'] == 1,
);

Map<String, dynamic> _$StockVOToJson(
  StockVO instance,
  String currentShopfront,
) => <String, dynamic>{
  'stock_id': instance.stockID,
  'shopfront': currentShopfront, // Composite Key part
  'Barcode': instance.barcode,
  'description': instance.description,
  'dept_name': instance.deptName,
  'dept_id': instance.deptID,
  'custom1': instance.custom1,
  'custom2': instance.custom2,
  'longdesc': instance.longDescription,
  'supplier': instance.supplier,
  'cat1': instance.category1,
  'cat2': instance.category2,
  'cat3': instance.category3,
  'cost': instance.cost,
  'sell': instance.sell,
  'inactive': instance.inactive ? 1 : 0,
  'quantity': instance.quantity,
  'layby_qty': instance.laybyQuantity,
  'salesorder_qty': instance.salesOrderQuantity,
  'date_created': instance.dateCreated,
  'order_threshold': instance.orderThreshold,
  'order_quantity': instance.orderQuantity,
  'allow_fractions': instance.allowFractions ? 1 : 0,
  'package': instance.package ? 1 : 0,
  'static_quantity': instance.staticQuantity ? 1 : 0,
  'picture_file_name': instance.pictureFileName,
  'imageUrl': instance.imageUrl,
  'goods_tax': instance.goodsTax,
  'sales_tax': instance.salesTax,
  'date_modified': instance.dateModified,
  'freight': instance.freight ? 1 : 0,
  'tare_weight': instance.tareWeight,
  'unitof_measure': instance.unitOfMeasure,
  'weighted': instance.weighted ? 1 : 0,
  'track_serial': instance.trackSerial ? 1 : 0,
};